### ISSUE TITLE
Fails: brew test circos

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-science#357]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
#### Brief summary of issue:
Fails:
```
$ brew test circos
```
#### The complete command that you issued:
```
$ brew test circos
Testing homebrew/science/circos
==> /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/bin/circos -conf /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/example/e
Last 15 lines from /home/linuxbrew/.logs/circos/test.01.circos:
2017-11-23 18:15:38 -0800

/home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/bin/circos
-conf
/home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/example/etc/circos.conf
-debug_group
summary,timer

Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/_{ <-- HERE ([^}]+)}/ at /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/bin/../lib/Circos/SVG.pm line 246.
Compilation failed in require at /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/bin/../lib/Circos.pm line 88.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/bin/../lib/Circos.pm line 88.
Compilation failed in require at /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/bin/circos line 340.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/bin/circos line 340.
Error: homebrew/science/circos: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/bin/circos -conf /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/example/etc/circos.conf -debug_group summary,timer
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1796:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1734:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1734:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/circos.rb:88:in `block in <class:Circos>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1640:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:557:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:36:in `block in <main>'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:35:in `<main>'
```
#### Gist with output of `brew doctor`:
```
$ brew dr
Your system is ready to brew.
```
#### Link output by `brew gist-logs <formula>`:
NA
#### Output of `brew config`:
```
$ brew config
HOMEBREW_VERSION: 1.3.7-14511-gfbc16c2
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: fbc16c2b5b62baea3e63bac5bf2e82f1e75126df
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 2b2a5e12caad0a3bfa699a7cc5f938cf9ba30b1b
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/linuxbrew/.cache
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_FILE: /home/linuxbrew/.linuxbrew/Homebrew/.git/config
HOMEBREW_LOGS: /home/linuxbrew/.logs
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_TEMP: /home/linuxbrew/.temp
HOMEBREW_VISUAL: /usr/bin/env vim
CPU: octa-core 64-bit merom
Homebrew Ruby: 2.4.2 => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Clang: 5.0 build
Git: 2.15.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.56.1 => /home/linuxbrew/.linuxbrew/opt/curl/bin/curl
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Java: 9.0.1
Kernel: Linux 2.6.32-504.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago) (Santiago)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.4.0
xorg: 20170115
```

**Comment by sjackman** [comment]
That looks like an upstream bug to me. Please report it to the upstream author.
This warning became an error with Perl 5.26.
See https://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated

**Comment by jwhite007** [comment]
Thanks, Shaun. In the future with these types I'll post upstream.

**Comment by sjackman** [comment]
I see that there's a new release of Circos 0.69-6 http://circos.ca/software/download/
I wouldn't be surprised if that fixes this issue. A PR for the new version would be welcome.
Use `brew edit circos` to change the `url` and `sha256`.
Note that this repository Linuxbrew/science is defunct. The PR should be sent to https://github.com/Homebrew/homebrew-science

**Comment by jwhite007** [comment]
Thanks, Shaun. I'm currently working on the PR. This will be my first.

**Comment by jwhite007** [comment]
Noob question...
Looks like I can just do the following. Right?...
```
$ brew bump-formula-pr circos --url=http://circos.ca/distribution/circos-0.69-6.tgz --sha256=52d29bfd294992199f738a8d546a49754b0125319a1685a28daca71348291566 --message="developer's bug fix"
```
Does this command determine that the correct repo is "https://github.com/Homebrew/homebrew-science"?

**Comment by jwhite007** [comment]
Dry run...
```
$ brew bump-formula-pr circos --dry-run --audit --strict --url=http://circos.ca/distribution/circos-0.69-6.tgz --sha256=52d29bfd294992199f738a8d546a49754b0125319a1685a28daca71348291566 --message="developer's bug fix"
==> brew update
==> replace / +mirror \"http:\/\/science-annex.org\/pub\/circos\/circos-0.67-7.tgz\"\n/m with ""
==> replace "http://circos.ca/distribution/circos-0.67-7.tgz" with "http://circos.ca/distribution/circos-0.69-6.tgz"
==> replace "6e1fc82e1f2f74056fa3229eb43f069e5813e911e9d75e6267f5e1e569a87b49" with "52d29bfd294992199f738a8d546a49754b0125319a1685a28daca71348291566"
==> brew audit --strict circos.rb
==> brew install hub
==> git fetch --unshallow origin
==> git checkout --no-track -b circos-0.69-6 origin/master
==> git commit --no-edit --verbose --message='circos 0.69-6' -- /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/circos.rb
==> hub fork # read $HUB_REMOTE
==> git push --set-upstream $HUB_REMOTE circos-0.69-6:circos-0.69-6
==> hub pull-request --browse -m 'circos 0.69-6'
==> git checkout -
```

**Comment by sjackman** [comment]
Looks good to me! Yes, the repo is correct above. I think `--sha256` may be optional if it can calculate it itself.

**Comment by jwhite007** [comment]
Unfortunately what I've posted above does not work. I get an error. ```Error: circos: no tag/revision specified!``` I find this very odd because ```--help``` for this command states ```(--url=URL --sha256=sha-256|--tag=tag --revision=revision)``` which I take to mean that either ```--url --sha256``` or ```--tag --revision``` can be used. I don't even know how to go about determining tag and revision. The circos formula doesn't have either of those.

**Comment by sjackman** [comment]
Try…
```sh
brew bump-formula-pr --url=http://circos.ca/distribution/circos-0.69-6.tgz circos
```
and omit the other options. Their defaults should be good.

**Comment by jwhite007** [comment]
Previously, I had tried that as well... same error.

**Comment by sjackman** [comment]
I got this error:
```
❯❯❯ brew bump-formula-pr --url=http://circos.ca/distribution/circos-0.69-6.tgz homebrew/science/circos
==> Downloading http://circos.ca/distribution/circos-0.69-6.tgz
Already downloaded: /Users/sjackman/Library/Caches/Homebrew/circos-0.69-6.tgz
Updated Homebrew from 639707c85 to f7baa3b38.
No changes to formulae.
==> replace / +mirror \"http:\/\/science-annex.org\/pub\/circos\/circos-0.67-7.t
==> replace "http://circos.ca/distribution/circos-0.67-7.tgz" with "http://circo
==> replace "6e1fc82e1f2f74056fa3229eb43f069e5813e911e9d75e6267f5e1e569a87b49" w
Error: cannot get remote from 'hub'!
```
Which looks like a bug in `bump-formula-pr`. I worked around it with…
```sh
git -C $(brew --repo homebrew/science) remote remove sjackman
brew bump-formula-pr --url=http://circos.ca/distribution/circos-0.69-6.tgz homebrew/science/circos
```
That worked for me.
